name: Print Repository Variable

on:
  workflow_dispatch:  # Manual trigger

jobs:
  print-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Repo Variable
        shell: bash
        run: echo "The value of NAME is: $NAME"
        env:
          NAME: ${{ vars.NAME }}
