name: Reveal Secret

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  reveal-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Encode Secret
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo "$SUPER_SECRET" | base64 > secret.txt

      - name: Upload Encoded Secret as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: secret-file
          path: secret.txt
          retention-days: 1  # Auto-delete after 1 day

      - name: Print GitHub Repo Variable
        shell: bash
        run: echo "The value of NAME is: $NAME"
        env:
          NAME: ${{ vars.NAME }}
