name: Print Repository Variable

on:
  push:
    branches:
      - variabeltesting  # Make sure this branch exists

jobs:
  print-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Repo Variable
        shell: bash
        env:
          NAME: "${{ vars.NAME }}"  # Ensure variable is correctly formatted
        run: echo "The value of NAME is: $NAME"
